logo:
  path: ''
  url: 'http://dev-brookgreend8.pantheonsite.io/themes/custom/bot_custom/logo.svg'
  use_default: true
schemas:
  bootstrap: 8000
  botparent: 8000
  bot_custom: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'http://dev-brookgreend8.pantheonsite.io/themes/custom/bot_custom/favicon.ico'
  use_default: true
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content_top: ''
  content: ''
  content_bottom: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
cdn_provider: jsdelivr
cdn_theme: flatly
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
  logo: true
  name: true
  slogan: true
