cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'http://dev-brookgreend8.pantheonsite.io/sites/default/files/favicon.ico'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
  logo: true
  name: true
  slogan: true
logo:
  path: ''
  url: 'http://dev-brookgreend8.pantheonsite.io/themes/contrib/bootstrap/logo.svg'
  use_default: true
schemas:
  bootstrap: 8000
  botparent: 8000
